version: "3"

services:
  reverse-proxy:
    image: nginx:stable
    ports:
      - "127.0.0.1:9100:80"
    volumes:
      - backend_dist_data:/backend_dist/
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stop_signal: SIGKILL
    env_file:
      - prod.env
    depends_on:
      - backend
    volumes:
      - frontend_dist_data:/frontend/dist/
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    stop_signal: SIGINT
    env_file:
      - prod.env
    depends_on:
      - db
    volumes:
      - backend_dist_data:/backend/_deployment/
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - prod.env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  frontend_dist_data:
  backend_dist_data:
  postgres_data:
