version: "3.4"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - dev.env
    stop_signal: SIGKILL
    volumes:
      - .:/workspace:cached
      - frontend_vscode_server:/home/appuser/.vscode-server
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - dev.env
    stop_signal: SIGKILL
    volumes:
      - .:/workspace:cached
      - backend_vscode_server:/home/appuser/.vscode-server
    depends_on:
      - db
  db:
    image: postgres:13-bullseye
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - dev.env

volumes:
  postgres_data_dev:
  backend_vscode_server:
  frontend_vscode_server:
