version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.dev.sh
    ports:
      - 8000:8000
    env_file:
      - dev.env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - dev.env

volumes:
  postgres_data_dev:
