version: "3"

services:
  reverse-proxy:
    image: nginx:stable
    ports:
      - 8100:80
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.dev.sh
    ports:
      - 8099:8080
    env_file:
      - dev.env
    depends_on:
      - backend
    volumes:
      # To allow hot reloading
      - ./frontend/public/:/frontend/public/
      - ./frontend/src/:/frontend/src/
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.dev.sh
    ports:
      - 8098:8000
    env_file:
      - dev.env
    stop_signal: SIGINT
    depends_on:
      - db
    volumes:
      # To allow hot reloading
      - ./backend/config/:/backend/config/
      - ./backend/repeaters/:/backend/repeaters/
      - ./backend/templates/:/backend/templates/
      - ./backend/users/:/backend/users/
  db:
    image: postgres:13-bullseye
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - dev.env

volumes:
  postgres_data_dev:
