version: "3.4"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - dev.env
    stop_signal: SIGKILL
    volumes:
      - ./frontend:/frontend
      - frontend_vscode_server:/root/.vscode-server
      - frontend_node_modules:/frontend/node_modules
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - dev.env
    stop_signal: SIGKILL
    volumes:
      - ./backend:/backend
      - backend_vscode_server:/root/.vscode-server/
      - backend_deployment:/backend/_deployment/
    depends_on:
      - db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  db:
    image: postgres:15
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - dev.env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  postgres_data_dev:
  backend_vscode_server:
  backend_deployment:
  frontend_vscode_server:
  frontend_node_modules:
