version: "3"

services:
  reverse-proxy:
    image: nginx:stable
    ports:
      - 8100:80
    volumes:
      - frontend_dist_data:/frontend_dist/
      - backend_dist_data:/backend_dist/
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: ./frontend/entrypoint.prod.sh
    stop_signal: SIGKILL
    env_file:
      - prod.env
    depends_on:
      - backend
    volumes:
      - frontend_dist_data:/workspace/frontend/dist/
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ./backend/entrypoint.prod.sh
    stop_signal: SIGINT
    env_file:
      - prod.env
    depends_on:
      - db
    volumes:
      - backend_dist_data:/workspace/backend/_deployment/
  db:
    image: postgres:13-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - prod.env

volumes:
  frontend_dist_data:
  backend_dist_data:
  postgres_data:
