version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.dev.sh
    ports:
      - 8080:8080
    env_file:
      - dev.env
    depends_on:
      - backend
    volumes:
      # To allow hot reloading
      - ./frontend/public:/node/public
      - ./frontend/src:/node/src
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.dev.sh
    ports:
      - 8000:8000
    env_file:
      - dev.env
    depends_on:
      - db
    volumes:
      - django_files_dev:/django_files/
  db:
    image: postgres:13-bullseye
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - dev.env

volumes:
  postgres_data_dev:
  django_files_dev:
