name: djangoenv
channels:
  - conda-forge
  - defaults
dependencies:
  - psycopg2
  - djangorestframework
  - pylint-django
  - dj-rest-auth
  - python
  - pylint
  - django-cors-headers
  - django
  - django-filter
  # - django-ckeditor # not available in conda
  - black
  - pyyaml
  - "pillow"
  - uritemplate
