# Generated by Django 3.2.10 on 2021-12-31 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_factpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factpdf',
            name='file',
            field=models.FileField(max_length=255, upload_to='pdfs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
