# Generated by Django 3.2.10 on 2022-01-04 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_factpdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(max_length=255, upload_to='pdfs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])])),
            ],
            options={
                'verbose_name': 'audio file',
                'verbose_name_plural': 'audio files',
            },
        ),
        migrations.AlterModelOptions(
            name='factblogpost',
            options={'verbose_name': 'blog post', 'verbose_name_plural': 'blog posts'},
        ),
        migrations.AlterModelOptions(
            name='factimage',
            options={'verbose_name': 'image file', 'verbose_name_plural': 'image files'},
        ),
        migrations.AlterModelOptions(
            name='factpdf',
            options={'verbose_name': 'PDF file', 'verbose_name_plural': 'PDF files'},
        ),
        migrations.AlterField(
            model_name='factimage',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='factpdf',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
