# Generated by Django 3.2.10 on 2022-01-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20220105_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factexamquestion',
            name='category',
            field=models.CharField(choices=[('1', 'Category 1'), ('2', 'Category 2'), ('3', 'Category 3')], max_length=5),
        ),
    ]
