# Generated by Django 4.2.4 on 2023-08-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abrv",
                    models.CharField(max_length=16, unique=True, verbose_name="abrv."),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=512, verbose_name="name"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "info - holder",
                "verbose_name_plural": "info - holders",
            },
        ),
    ]
