# Generated by Django 4.2.4 on 2023-08-24 17:10

from django.db import migrations


def copy_data_between_tables(apps, _):
    # We can't import the models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    DimHolder = apps.get_model("repeaters", "DimHolder")
    Association = apps.get_model("associations", "Association")
    for holder in DimHolder.objects.all():
        association = Association(
            id=holder.id,
            abrv=holder.abrv,
            name=holder.name,
            email=holder.email,
            website=holder.website,
            notes=holder.notes,
        )
        association.save()


class Migration(migrations.Migration):
    dependencies = [
        ("associations", "0001_initial"),
        ("repeaters", "0002_dimholder_email_dimholder_notes_dimholder_website"),
    ]

    operations = [
        migrations.RunPython(copy_data_between_tables),
    ]
