# Generated by Django 4.2.4 on 2023-08-24 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("associations", "0002_copy_data_from_dimholder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="association",
            options={
                "verbose_name": "Association",
                "verbose_name_plural": "Associations",
            },
        ),
    ]
