# Generated by Django 4.2.4 on 2023-08-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repeaters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimholder",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="e-mail"),
        ),
        migrations.AddField(
            model_name="dimholder",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AddField(
            model_name="dimholder",
            name="website",
            field=models.URLField(blank=True, verbose_name="website"),
        ),
    ]
