# Generated by Django 3.2.10 on 2022-01-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repeaters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factrepeater',
            name='status',
            field=models.CharField(choices=[('OFF', 'off'), ('ON', 'on'), ('PROJECT', 'project'), ('PROBLEMS', 'problems'), ('OT', 'other')], default='OT', max_length=50, verbose_name='status'),
        ),
    ]
