# Generated by Django 4.2.4 on 2023-08-24 12:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("repeaters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimlocation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
