# Generated by Django 3.2.10 on 2021-12-22 00:34

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repeaters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factrepeater',
            name='notes',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='notes'),
        ),
    ]
