# Generated by Django 3.2.10 on 2021-12-23 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repeaters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimDmrTg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('dmr_id', models.IntegerField(unique=True, verbose_name='DMR ID')),
            ],
            options={
                'verbose_name': 'info - DMR TG',
                'verbose_name_plural': 'info - DMR TG',
            },
        ),
        migrations.RemoveField(
            model_name='dimdmr',
            name='ts1_tgs',
        ),
        migrations.RemoveField(
            model_name='dimdmr',
            name='ts2_tgs',
        ),
        migrations.AddField(
            model_name='dimdmr',
            name='ts1_alternative_tgs',
            field=models.ManyToManyField(blank=True, related_name='dimdmr_ts1_alternative_tgs', to='repeaters.DimDmrTg'),
        ),
        migrations.AddField(
            model_name='dimdmr',
            name='ts1_default_tg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimdmr_ts1_default_tg', to='repeaters.dimdmrtg'),
        ),
        migrations.AddField(
            model_name='dimdmr',
            name='ts2_alternative_tgs',
            field=models.ManyToManyField(blank=True, related_name='dimdmr_ts2_alternative_tgs', to='repeaters.DimDmrTg'),
        ),
        migrations.AddField(
            model_name='dimdmr',
            name='ts2_default_tg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimdmr_ts2_default_tg', to='repeaters.dimdmrtg'),
        ),
    ]
