# Generated by Django 3.2.13 on 2022-04-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repeaters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimholder',
            name='sysop',
        ),
        migrations.AddField(
            model_name='factrepeater',
            name='sysop',
            field=models.CharField(blank=True, max_length=20, verbose_name='sysop'),
        ),
    ]
