# Generated by Django 4.2.4 on 2023-08-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("associations", "0003_alter_association_options"),
        ("repeaters", "0002_dimholder_email_dimholder_notes_dimholder_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="factrepeater",
            name="info_holder_temp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="associations.association",
                verbose_name="info - holder",
            ),
        ),
    ]
