# Generated by Django 3.2.10 on 2021-12-22 09:23

import django.contrib.postgres.fields
from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repeaters', '0002_alter_factrepeater_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimdmr',
            name='ts1_configuration',
        ),
        migrations.RemoveField(
            model_name='dimdmr',
            name='ts2_configuration',
        ),
        migrations.AddField(
            model_name='dimdmr',
            name='ts1_tg_default',
            field=models.IntegerField(blank=True, null=True, verbose_name='TS1 default TG'),
        ),
        migrations.AddField(
            model_name='dimdmr',
            name='ts1_tgs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None, verbose_name='TS1 TGs'),
        ),
        migrations.AddField(
            model_name='dimdmr',
            name='ts2_tg_default',
            field=models.IntegerField(blank=True, null=True, verbose_name='TS2 default TG'),
        ),
        migrations.AddField(
            model_name='dimdmr',
            name='ts2_tgs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None, verbose_name='TS2 TGs'),
        ),
        migrations.AddField(
            model_name='dimdmr',
            name='ts_configuration',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='TS config.'),
        ),
    ]
