# Generated by Django 3.2.13 on 2022-04-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repeaters', '0002_auto_20220426_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimfm',
            name='bandwidth',
            field=models.CharField(choices=[('NFM', 'nfm'), ('WFM', 'wfm')], default='NFM', max_length=50, verbose_name='bandwidth'),
        ),
    ]
