# Generated by Django 4.2.4 on 2023-08-24 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("repeaters", "0003_dimlocation_transform_latlong_location"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dimlocation",
            name="unique lat./long. combination",
        ),
        migrations.RemoveField(
            model_name="dimlocation",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="dimlocation",
            name="longitude",
        ),
    ]
