# Generated by Django 3.2.13 on 2022-04-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repeaters', '0003_dimfm_bandwidth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimfm',
            name='bandwidth',
            field=models.CharField(choices=[('NFM', 'NFM'), ('WFM', 'WFM')], default='NFM', max_length=50, verbose_name='bandwidth'),
        ),
        migrations.AlterField(
            model_name='factrepeater',
            name='status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON'), ('PROJECT', 'PROJECT'), ('PROBLEMS', 'PROBLEMS'), ('OT', 'other')], default='OT', max_length=50, verbose_name='status'),
        ),
    ]
