# Generated by Django 4.2.4 on 2023-08-24 17:22

from django.db import migrations


def copy_data_between_tables(apps, _):
    # We can't import the models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    FactRepeater = apps.get_model("repeaters", "FactRepeater")
    Association = apps.get_model("associations", "Association")
    for repeater in FactRepeater.objects.all():
        if repeater.info_holder is not None:
            repeater.info_holder_temp = Association.objects.get(
                id=repeater.info_holder.id
            )
            repeater.save()


class Migration(migrations.Migration):
    dependencies = [
        ("repeaters", "0003_factrepeater_info_holder_temp"),
        ("associations", "0003_alter_association_options"),
    ]

    operations = [
        migrations.RunPython(copy_data_between_tables),
    ]
