# Generated by Django 4.2 on 2023-04-25 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("repeaters", "0004_auto_20220426_1509"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimdmr",
            name="ts1_alternative_tgs",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_ts1_alternative_tgs",
                to="repeaters.dimdmrtg",
            ),
        ),
        migrations.AlterField(
            model_name="dimdmr",
            name="ts1_default_tg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_ts1_default_tg",
                to="repeaters.dimdmrtg",
            ),
        ),
        migrations.AlterField(
            model_name="dimdmr",
            name="ts2_alternative_tgs",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_ts2_alternative_tgs",
                to="repeaters.dimdmrtg",
            ),
        ),
        migrations.AlterField(
            model_name="dimdmr",
            name="ts2_default_tg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_ts2_default_tg",
                to="repeaters.dimdmrtg",
            ),
        ),
    ]
