# Generated by Django 4.2.4 on 2023-08-24 13:36

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("repeaters", "0004_remove_dimlocation_unique_lat_long_combination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimlocation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                default=django.contrib.gis.geos.point.Point(40.3, -7.6),
                srid=4326,
            ),
        ),
    ]
