# Generated by Django 4.2.4 on 2023-08-24 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("repeaters", "0006_rename_info_holder_temp_factrepeater_info_holder"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DimHolder",
        ),
    ]
