# Generated by Django 4.2.4 on 2023-08-24 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("repeaters", "0008_dimtetra_alter_factrepeater_modes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dimdmr",
            name="modulation",
        ),
        migrations.RemoveField(
            model_name="dimdstar",
            name="modulation",
        ),
        migrations.RemoveField(
            model_name="dimfusion",
            name="modulation",
        ),
    ]
