# Generated by Django 4.2.4 on 2023-08-26 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "repeaters",
            "0009_remove_dimdmr_modulation_remove_dimdstar_modulation_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DimDStar",
            new_name="DimDstarTriggerMigration",
        ),
    ]
