# Generated by Django 4.2.4 on 2023-08-26 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("repeaters", "0010_rename_dimdstar_dimdstartriggermigration"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DimDstarTriggerMigration",
            new_name="DimDstar",
        ),
    ]
