# Generated by Django 4.2.4 on 2023-08-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repeaters", "0011_rename_dimdstartriggermigration_dimdstar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimlocation",
            name="qth_loc",
            field=models.CharField(
                blank=True, editable=False, max_length=32, verbose_name="QTH loc."
            ),
        ),
    ]
