# Generated by Django 4.2.5 on 2023-09-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repeaters", "0013_remove_dimfm_unique_mod_tone_combination_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dimfm",
            name="unique mod./tone/SQL combination",
        ),
        migrations.RenameField(
            model_name="dimfm",
            old_name="tone",
            new_name="ctcss",
        ),
        migrations.AddConstraint(
            model_name="dimfm",
            constraint=models.UniqueConstraint(
                fields=("modulation", "ctcss", "tone_sql"),
                name="unique mod./tone/SQL combination",
            ),
        ),
    ]
