# Generated by Django 4.2.5 on 2023-09-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repeaters", "0014_remove_dimfm_unique_mod_tone_sql_combination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimfm",
            name="ctcss",
            field=models.DecimalField(
                blank=True,
                decimal_places=16,
                max_digits=32,
                null=True,
                verbose_name="CTCSS",
            ),
        ),
    ]
