# Generated by Django 4.2.5 on 2023-09-07 07:29

from django.db import migrations


def copy_data_between_tables(apps, _):
    # We can't import the models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    DimFm = apps.get_model("repeaters", "DimFm")
    for info_fm in DimFm.objects.all():
        # Treat tones above 1000Hz as a pilot tone
        if info_fm.ctcss and info_fm.ctcss > 999.99:
            info_fm.transit_pilot = info_fm.ctcss
            info_fm.ctcss = None
            info_fm.ctcss_sql = False
        info_fm.save()


class Migration(migrations.Migration):
    dependencies = [
        ("repeaters", "0018_remove_dimfm_unique_mod_tone_sql_combination_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_data_between_tables),
    ]
