# Generated by Django 4.2.7 on 2023-11-24 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("repeaters", "0019_move_tones_to_pilots"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dimdmr",
            name="ts1_default_tg",
        ),
        migrations.RemoveField(
            model_name="dimdmr",
            name="ts2_default_tg",
        ),
    ]
