# Generated by Django 4.2.7 on 2023-11-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repeaters", "0021_rename_tg_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimdmr",
            name="ts1_tgs",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_ts1_tgs", to="repeaters.dimdmrtg"
            ),
        ),
        migrations.AlterField(
            model_name="dimdmr",
            name="ts2_tgs",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_ts2_tgs", to="repeaters.dimdmrtg"
            ),
        ),
    ]
